language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Vx76DorSRi2V89AFt1AhY3ZaszU9oYTHsbjkgbMCiYf2mzEy3nQSNDru3gsEkDeo+rNINDjxpReP8K/5OycKdL9xwWBkRmd5fZWIy7ZmFv9yQ6Xa5LIYa2JEDO+iF/gNQYDHXB1QaKLDhCtqltyCEJwb6tygaFzsBP7HtyaQ4zOt1TDKnlEOVYzveUqGrttqU0cMQrY0/6o5Kny+QlJ1ygtECTzgzU80opytUCItcT1V99huR2CNDaKjpjZpttkB69HfMjKcdDLKYt/BpHef4//5mPZrNA0Fq0iVr2QXgi4Ub3LIM9UCPJ16Tms1GRFgV82jPWBsnoI+CfRMyZNxjlgtp0nCKHyFEgG9TR8WnLxpGaKIxzyDdAfMHpGZrsYnfzHuyASGguYVEe2Hu5vlMV5OC1Toefjfw2s2XdDLpbwgKvHc8yDBvSXfntPgxHkCu2HJ69E9JN+NtSCmKBECpvkZGuwaQJ+4KY5uwNx22a5Rz3n3zdKUd3m9/ME72KTia7Am7AEJuXLDaXzHbBOib+Wx0so7JZvtCTZzwQPrl2BaBRWoFDUmPthAjff/XTn68ntiIs3o8P7K+1osyy5n8soCRhaTNc5pwh9kay85vL6c7QTW1dCVJN23uDwBBbz5pp4QfeW1EkC8H9Aco2LGtD3K5ofRUHPbxuEzCsGf2qk=
  app: glacial-wildwood-37638
  on:
    repo: drerichards/vendible-server
